apiVersion: v1
kind: Service
metadata:
  name: my-app1-service
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: "nlb"
    service.beta.kubernetes.io/aws-load-balancer-backend-protocol: "http"
spec:
  type: LoadBalancer
  ports:
      targetPort: 8000
      protocol: TCP
      name: http
  selector:
    app: my-app1