name: CICD

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment:
      AWS_REGION: ap-south-1
      ECR_REPOSITORY: profiles-rest-api
      EKS_CLUSTER: profiles-rest-api-eks-cluster
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Login to ECR
        uses: aws-actions/login-to-ecr@v1

      - name: Build and push Docker image
        run: |
          docker build -t $ECR_REPOSITORY:latest .
          docker tag $ECR_REPOSITORY:latest $AWS_REGION.dkcr.ecr.$AWS_REGION.amazonaws.com/$ECR_REPOSITORY:latest
          docker push $AWS_REGION.dkcr.ecr.$AWS_REGION.amazonaws.com/$ECR_REPOSITORY:latest

      - name: Configure kubectl
        uses: aws-actions/configure-eks-cluster@v1
        with:
          cluster-name: ${{ env.EKS_CLUSTER }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Apply deployment and service
        run: |
          kubectl apply -f deployment.yaml
          kubectl apply -f service.yaml
        env:
          EKS_CLUSTER: ${{ env.EKS_CLUSTER }}
          ECR_REPOSITORY: ${{ env.ECR_REPOSITORY }}
          AWS_REGION: ${{ env.AWS_REGION }}

      - name: Verify deployment
        run: |
          kubectl get deployments
          kubectl get pods
          kubectl get svc